stages:
  - name: setup_code
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        home: '$REANA_WORKSPACE'
        release: 'CMSSW_10_6_12'
        scram_arch: 'slc7_amd64_gcc700'
      step: {$ref: workflow/steps.yaml#/setup_code}

  - name: produce_ntuple
    dependencies: [create_PU_dist]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        input_file_PU: {step: 'init', output: PU_files, unwrap: true}
        input_file_noPU: {step: 'init', output: noPU_files, unwrap: true}
        algo: 'AK'
        cone_size: '8'
        jet_type: 'PFchs'
        release: 'CMSSW_10_6_12'
        scram_arch: 'slc7_amd64_gcc700'
      workflow: {$ref: workflow/workflow_ntuple.yaml}